--DAY 3 LAB PRACTICE

-- EX1 - ANANYMOUS BLOCK TO PRINT MESSAGE
BEGIN
    DBMS_OUTPUT.PUT_LINE('Today is Tuesday');
END;

--EX2 - ANANYMOUS BLOCK TO PRINT TODAY'S DATE

DECLARE
TDATE DATE;
BEGIN 
    SELECT SYSDATE INTO tdate FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('TODAY->'||SYSDATE);
    DBMS_OUTPUT.PUT_LINE('TODAY->'||tdate);
END;


--EX3 - PRODUCT PROCE BASED ON USER INPUT
DECLARE 
VAR_INPUT NUMBER(2);
VAR_PRICE stores.prod_price%TYPE;
VAR_ITEM stores.prod_name%TYPE;
BEGIN
    SELECT PROD_PRICE ,PROD_NAME INTO VAR_PRICE ,VAR_ITEM FROM STORES WHERE PROD_ID = &VAR_INPUT;
    DBMS_OUTPUT.put_line(VAR_ITEM ||' IS ' || var_price || ' Rs.');
END;

